### ISSUE TITLE
TreeView ContextMenu not fired events

### ISSUE THREAD

**Issue by ghost** [vcaraulean/Caliburn.Micro.Telerik#16]
Please help me, Thanks so much.

Resource =>

```
    <HierarchicalDataTemplate x:Key="TreeViewItemTemplate" ItemsSource="{Binding Types}"
        ItemTemplateSelector="{StaticResource NamespaceItemTemplateSelector}">
    <StackPanel Orientation="Horizontal">
        <Path
                Data=""
                Height="11.458" Margin="0,0,5,0" RenderTransformOrigin="0.5,0.5" Stretch="Fill"
                UseLayoutRounding="False" Width="11.264">
            <Path.Fill>
                <SolidColorBrush Color="#FF333333">
                    <SolidColorBrush.RelativeTransform>
                        <MatrixTransform Matrix="Identity" />
                    </SolidColorBrush.RelativeTransform>
                    <SolidColorBrush.Transform>
                        <MatrixTransform Matrix="Identity" />
                    </SolidColorBrush.Transform>
                </SolidColorBrush>
            </Path.Fill>
            <Path.RenderTransform>
                <TransformGroup>
                    <ScaleTransform />
                    <SkewTransform />
                    <RotateTransform />
                    <TranslateTransform />
                </TransformGroup>
            </Path.RenderTransform>
        </Path>
        <TextBlock Text="{Binding Header}" Tag="{Binding DataContext, RelativeSource={RelativeSource Self}}">
       <telerik:RadContextMenu.ContextMenu>
     <telerik:RadContextMenu cal:Action.TargetWithoutContext="{Binding RelativeSource={RelativeSource Self},             Path=UIElement.Tag}" cal:Message.Attach="[Event Opened] = [Action Opened($dataContext)]" >
           <telerik:RadMenuItem Header="New Child" cal:Message.Attach="ShowProperties($datacontext)"/>
        <telerik:RadMenuItem Header="New Sibling" />
          <telerik:RadMenuItem Header="Delete" />
             </telerik:RadContextMenu>
      </telerik:RadContextMenu.ContextMenu>
        </TextBlock>
    </StackPanel>
</HierarchicalDataTemplate>
```

RadTreeView =>

```
    <telerik:RadTreeView x:Name="RadTreeView" BorderThickness="0" Margin="5" Background="White" Width="500"                 telerik:AnimationManager.IsAnimationEnabled="False" IsVirtualizing="True" telerik:StyleManager.Theme="Windows8"                         ItemTemplate="{StaticResource TreeViewItemTemplate}"                            ItemContainerStyle="{StaticResource TreeViewItemStyle}"
                            ItemsSource="{Binding Namespaces}"/>
```

**Comment by ghost** [comment]
Hi, ContextMenu convention for RadTreeView not fired events, I think bug in ContextMenu convention.

**Comment by vcaraulean** [comment]
Have you tried to get it working without any convention? Conventions are just a helper...

**Comment by ghost** [comment]
Upload project please see this project contextmenu not fired event, I'm trying standard ContextMenu not solved problem. Thanks a lot.

http://bayfiles.net/file/STqD/MekWE9/TreeViewSample.rar

**Comment by ghost** [comment]
After click MenuItem this error.

   at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   at System.Windows.Interactivity.TriggerAction.CallInvoke(Object parameter)
   at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   at System.Windows.Interactivity.EventTriggerBase.OnEvent(EventArgs eventArgs)
   at System.Windows.Interactivity.EventTriggerBase.OnEventImpl(Object sender, EventArgs eventArgs)

**Comment by ghost** [comment]
Hi vcaraulean, Thanks solved my problem.
